### ISSUE TITLE
Consider migrating sample to flask's click-based cli

### ISSUE THREAD

**Issue by JulienPalard** [shijl0925/Flask-AdminLTE3#7]
As flask-script is no longer maintaned and no longer compatible with flask:

```python
$ python manage.py 
Traceback (most recent call last):
  File "/home/mdk/clones/Flask-AdminLTE3/sample_application/manage.py", line 4, in <module>
    from flask_script import Manager
  File "/home/mdk/clones/Flask-AdminLTE3/.venv/lib/python3.9/site-packages/flask_script/__init__.py", line 15, in <module>
    from flask._compat import text_type
ModuleNotFoundError: No module named 'flask._compat'
```

**Comment by shijl0925** [comment]
How to run
$ export FLASK_DEBUG=1
$ export FLASK_APP=apps
$ python3 -m flask run
